### ISSUE TITLE
How do you ensure that the new object is located close to the old object？

### ISSUE THREAD

**Issue by qpc1611094** [Bujiazi/MotionClone#21]
Nice work.
In your newest version, I have noticed that no DDIM Inversion and Location-Aware Semantic Guidance are needed.
But why can the generated results still keep the original video's location structure?
In this new version, are there failure cases like the one in Figure 5 of your old version?
![image](https://github.com/user-attachments/assets/0d62785d-7610-4578-b44e-a592adb2ff02)

**Comment by LPengYang** [comment]
Hi~, Thanks for your attention on our work. In the new version, the motion guidance is directly obtained from a single time step (default as 400), which contains richer motion information since it is closer to x0 while mainly capturing structures of each frames (can be valided by visualizing its predicted x0). Such substantial and consistent motion guidance helps alleviate ambiguity in model synthesis and thus facilitates enhanced motion-alignment and reasonable spatial layout (coarse spatial layout is perserved at x=400). However, affected by the stability of base model, failure may occurs, in which different initial noise is recommended. Generally, in our experiments, DDIM Inversion is not necessary in motion cloning and the effect of Location-Aware Semantic Guidance can be largely replaced by enhanced guidance, facilitating efficient and flexible motion customization.

**Comment by LPengYang** [comment]
> Nice work. In your newest version, I have noticed that no DDIM Inversion and Location-Aware Semantic Guidance are needed. But why can the generated results still keep the original video's location structure? In this new version, are there failure cases like the one in Figure 5 of your old version? ![image](https://private-user-images.githubusercontent.com/49224514/381375067-0d62785d-7610-4578-b44e-a592adb2ff02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzg0NDEsIm5iZiI6MTczMDI3ODE0MSwicGF0aCI6Ii80OTIyNDUxNC8zODEzNzUwNjctMGQ2Mjc4NWQtNzYxMC00NTc4LWI0NGUtYTU5MmFkYjJmZjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA4NDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzODE3OTk1MjBmZTljOWU3MWYwMzBiMWM4M2FlNGFlMThkMWVhYzFkYzEyYzM0MWQwYmU4ZTQ0ZGYwZTkxNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-sRYG3maAS67zyZQv9hxyjRnl24KaG3hq_pCvYWODaY)

Hi~, Thanks for your attention to our work. In the new version, the motion guidance is directly obtained from a single time step (default as 400), which contains richer motion information since it is closer to x0 while mainly capturing structures of each frame (can be validated by visualizing its predicted x0). Such substantial and consistent motion guidance helps alleviate ambiguity in motion synthesis and thus facilitates enhanced motion-alignment and reasonable spatial layout (coarse spatial layout is preserved at t=400). However, affected by the stability of the base model, failure may occur, in which different initial noise is recommended. Generally, in our experiments, DDIM Inversion is not necessary for motion cloning and the effect of Location-Aware Semantic Guidance can be largely replaced by enhanced guidance, facilitating efficient and flexible motion customization.
