### ISSUE TITLE
sample.py uses 45GB GPU RAM

### ISSUE THREAD

**Issue by askerlee** [Bujiazi/MotionClone#5]
First thanks for the amazing model.

When I ran it I noticed it took 45 GB of GPU RAM. Fortunately my GPU has a total RAM of 48GB. But I'm worried that this may prevent many people from using this model.

May I know what's the reason so much RAM is used? Is this because all the frames are processed at the same time? Any rough idea how to cut it down? Thanks.

**Comment by Bujiazi** [comment]
Thank you for your feedback. Currently, MotionClone utilizes higher GPU memory due to the following reasons:
- We have introduced classifier-free guidance for location-aware semantic guidance in video.
- Optimization of latents in MotionClone is **gradient-based**, which occupies a certain amount of GPU memory.
- We default to using higher resolution settings (now adjustable), which also contributes to GPU memory usage.

We will soon release a version that requires less GPU memory.

**Comment by LPengYang** [comment]
> First thanks for the amazing model.
> 
> When I ran it I noticed it took 45 GB of GPU RAM. Fortunately my GPU has a total RAM of 48GB. But I'm worried that this may prevent many people from using this model.
> 
> May I know what's the reason so much RAM is used? Is this because all the frames are processed at the same time? Any rough idea how to cut it down? Thanks.

Sorry for being late. We have updated the code. Now MotionClone is able to 1) directly performs motion customization without cumbersome video inversion ; 2) significantly reduces video memory consumption.
In our experiments, For 16×512×512 text-to-video, the memory consumption is about 14GB . For MotionClone combined with image-to-video and sketch-to-video, the memory is about 22 GB. Hope this helps.
